default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight (CI)"
  lane :ci_release do
    build_app(
      scheme: "App",
      workspace: "ios/App/App.xcworkspace",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "build",
      include_bitcode: false
    )

    upload_to_app_store(
      skip_metadata: true, skip_screenshots: true,
      submit_for_review: false,
      api_key: app_store_connect_api_key(
        key_id: ENV["ASC_KEY_ID"],
        issuer_id: ENV["ASC_ISSUER_ID"],
        key_content: ENV["ASC_KEY_CONTENT"],
        is_key_content_base64: true
      )
    )
  end
end
